language: java
script: mvn -P cli -P server package -DskipTests
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - ./install-SentenceSimplification.sh
  - ./install-DiscourseSimplification.sh
