version: '3'

services:

  coreference:
    depends_on:
      - corenlp
    image: "lambdacube/pycobalt:v1.1.1"
    environment:
      - PYCOBALT_CORENLP=http://corenlp:9000
    expose:
      - "5128"
    ports:
      - "5128:5128"
    links:
      - corenlp

  corenlp:
    image: "lambdacube/corenlp:3.7.0"
    expose:
      - "9000"
